name: just_another_workout_timer
description: Just Another Workout Timer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+20210307

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.3
  pref: ^2.0.0
  url_launcher: ^6.0.2
  wakelock: ^0.5.0+2
  soundpool: ^1.1.3
  scrollable_positioned_list:
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
  intl_utils: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_oss_licenses: ^1.0.0
  effective_dart:

dependency_overrides:
  http: ^0.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - LICENSE
    - assets/beep.wav

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/ic_launcher.png"

flutter_intl:
  enabled: true